### ISSUE TITLE
Shift + Return for soft returns.

### ISSUE THREAD

**Issue by oyeanuj** [SamyPesse/slate-edit-list#2]
Hey @SamyPesse, as per our conversation, here is the Github issue.

Doing `shift + return`, still carries forward the bullet point. It should act like a soft return without the bullet point IMO. `Mod + return` seems to do that here but `shift + return` is also fairly standard in other editors.

**Comment by SamyPesse** [comment]
Thanks, fixed by e96f2d4b2e617067c0ea95747662f318ff777aa9
